build: fix ng-packagr config. update to angular v6.
it's currently throwing the following when running in packaged mode
TypeError: Cannot read property 'init' of undefined
it may be due to Quagga using `export default`